import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center place-items-center h-96 text-3xl">
        <h1>
          Welcome to{" "}
          <Link href="/Login" className="underline text-blue-700">
            Next JS !
          </Link>
        </h1>
      </div>
    </>
  );
}
